# Favicon
favicon: /favicon.ico

# SEO
keywords:

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /blog
  Twitter: https://twitter.com/sea35xiongwe
  Weibo: https://www.weibo.com/romanchelsea
  Zhihu: https://www.zhihu.com/people/romanchelsea

# Nav menu
menu:
  Home: /
  Blog: /blog
  About: /about
